### ISSUE TITLE
Popover captures focus on presentation

### ISSUE THREAD

**Issue by ShezHsky** [aheze/Popovers#13] opened 2022-01-06 13:00 UTC
Presenting a popover causes it to capture focus, which for a lot of situations is desirable (e.g. when it contains other controls). However there are some use cases where a popover can provide supplementary information and should not take focus away. As an example for an app looking to use this library, validation of user input with constraints should explain why the input is rejected - a good use for a popover - but once the popover appears the user must manually tap on the control again to change their input.

https://user-images.githubusercontent.com/12624320/148385426-ed13c16f-7596-45f1-88c4-373c89138ed8.mov

Ideally the attributes for the popover should allow designating whether the popover should obtain focus when presented, or leave focus with the currently focused view (with the default being the former for compatibilities sake). This may require moving away from hosting the popover container view in a view controller, as its presentation will always mess up the currently focused view with it being a "modal" presentation.

I've [pushed a commit to my fork](https://github.com/ShezHsky/Popovers/commit/9bb637f3a281e22d0acce9f325aff21d93783d9f) for reproduction convenience

**Comment by aheze** [comment] 2022-01-06 14:42
Yeah this is a problem. I think the old window based approach had the same thing though. Maybe there is a property on view controller that stops it from stealing focus. Or as you said, maybe just adding the view controller’s view as a Subviews might work

**Comment by ShezHsky** [comment] 2022-01-06 16:17
> Maybe there is a property on view controller that stops it from stealing focus.

Aye I was hoping a cheeky change to `canBecomeFirstResponder` on the container view controller or its subviews would do the trick, but it seems as through the text field is forced to relinquish focus during presentation anyway. Makes some sense as the presentation is still modal, even though aesthetically this isn't the case with the visual passthrough.

Saying that, there will be some situations this behaviour remains desirable. Especially when using Voiceover or switch controls, where the popover is now the primary interaction point I'd expect it to continue to focus the contents of the popover as it does now. Supplementary information like in my validation example don't need focus, so being able to specify this client-side would be perfect.

**Comment by aheze** [comment] 2022-01-09 21:55
I've added some changes inside https://github.com/aheze/Popovers/tree/feature/directly-add-as-subview. The problem is, the popover isn't always on top. If a sheet is presented, it gets covered.

https://user-images.githubusercontent.com/49819455/148702533-1a5d7668-cc0f-492a-9415-e5d3b8423b30.mov

**Comment by aheze** [comment] 2022-01-09 21:57
This is probably because I'm using presenting the popover on the root view controller (which takes up the entire width and height of the screen). The actual topmost view controller could be a sheet, and then the frames get mispositioned since they are relative to the window. And sometimes I can't locate the popover model inside the responder chain.

https://github.com/aheze/Popovers/blob/afa2959b3de00c3be7bdb0cc9af2180c12e515e4/Sources/Popover%2BLifecycle.swift#L25-L26

**Comment by aheze** [comment] 2022-01-18 05:32
Fixed in [1.2.0](https://github.com/aheze/Popovers/releases/tag/1.2.0).

**Closed by aheze** 2022-01-18 05:32 UTC
Labels: bug, enhancement, help wanted
